### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by sunilsairam** [TimotheeJeannin/AppRate#2]
HI Timothee,

I am using your AppRate in my application.
But when ever I click on any button on the dialog, I am getting a null pointer at com.tjeannin.apprate.AppRate.onClick(AppRate.java:248).

I even tried your AppRateSample and got the same error. 
Can you help me out here?

Regards,
Sunil Sairam.

**Comment by TimotheeJeannin** [comment]
Hi @sunilsairam, 

Thank you for reporting this bug.

What version of AppRate are you using ? 
What version of Android are you testing with ? 
Can you post the stack trace ? 

Regards, 
Tim

**Comment by sunilsairam** [comment]
Hi Tim,

I am using your latest version of Apprate -- 1.0.
I am trying in Android 4.0.4 and using java 1.6.
I don't have the stack trace with me right now, will post it in a day or two.

Regards,
Sunil.

**Comment by TimotheeJeannin** [comment]
Thank you for those details. Waiting for the stack trace. :)

Regards, 
Tim

**Comment by sunilsairam** [comment]
03-11 22:58:23.287: D/AppRater(687): Init AppRate
03-11 22:58:23.287: D/AppRater(687): Init AppRate ExceptionHandler
03-11 22:58:23.477: D/gralloc_goldfish(687): Emulator without GPU emulation detected.
03-11 22:58:31.877: D/AppRater(687): Init AppRate
03-11 22:58:31.877: D/AppRater(687): Init AppRate ExceptionHandler
03-11 22:58:34.547: D/AppRater(687): Init AppRate
03-11 22:58:34.547: D/AppRater(687): Init AppRate ExceptionHandler
03-11 22:58:34.558: D/AppRater(687): Create default dialog.
03-11 22:58:34.727: D/dalvikvm(687): GC_CONCURRENT freed 215K, 4% free 8223K/8519K, paused 75ms+21ms, total 166ms
03-11 22:58:35.117: I/Choreographer(687): Skipped 76 frames!  The application may be doing too much work on its main thread.
03-11 22:58:36.317: I/Choreographer(687): Skipped 38 frames!  The application may be doing too much work on its main thread.
03-11 22:58:43.817: D/AndroidRuntime(687): Shutting down VM
03-11 22:58:43.817: W/dalvikvm(687): threadid=1: thread exiting with uncaught exception (group=0x40a13300)
03-11 22:58:43.847: E/AndroidRuntime(687): FATAL EXCEPTION: main
03-11 22:58:43.847: E/AndroidRuntime(687): java.lang.NullPointerException
03-11 22:58:43.847: E/AndroidRuntime(687):  at com.tjeannin.apprate.AppRate.onClick(AppRate.java:248)
03-11 22:58:43.847: E/AndroidRuntime(687):  at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
03-11 22:58:43.847: E/AndroidRuntime(687):  at android.os.Handler.dispatchMessage(Handler.java:99)
03-11 22:58:43.847: E/AndroidRuntime(687):  at android.os.Looper.loop(Looper.java:137)
03-11 22:58:43.847: E/AndroidRuntime(687):  at android.app.ActivityThread.main(ActivityThread.java:4745)
03-11 22:58:43.847: E/AndroidRuntime(687):  at java.lang.reflect.Method.invokeNative(Native Method)
03-11 22:58:43.847: E/AndroidRuntime(687):  at java.lang.reflect.Method.invoke(Method.java:511)
03-11 22:58:43.847: E/AndroidRuntime(687):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
03-11 22:58:43.847: E/AndroidRuntime(687):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
03-11 22:58:43.847: E/AndroidRuntime(687):  at dalvik.system.NativeStart.main(Native Method)
03-11 22:58:46.577: I/Process(687): Sending signal. PID: 687 SIG: 9

Please find above the stack trace. I tried it even in 4.1 emulator and got the same issue. Please help.
Also note that I am trying Apprate Sample, itself..

**Comment by TimotheeJeannin** [comment]
Ok this should be fixed now. :)

**Comment by sunilsairam** [comment]
Thanks Timothee. 
I will check it with the latest jar.
